### ISSUE TITLE
Off-By-One Error in Right-Hand Controller Semantic Mapping

### ISSUE THREAD

**Issue by nanospork** [lonetech/nolo-osvr#11]
The semantic mapping for the buttons is off-by one. Note that the left-hand controller, for example, is using buttons 0-5, and the right-hand controller is using 7-12. The right-hand controller should be using 6-11. The analog axes appear to be incorrect as well.

I would just submit a PR for this, but I can't get the plugin to build on Windows. I can't even apparently point it to hidapi.h properly? I'm not sure why it's so difficult, because building OSVR-Fusion was easy.

Perhaps a separate issue should be opened regarding building on Windows.

**Comment by Conzar** [comment]
I forked, and will fix the issue (hopefully).

**Comment by Conzar** [comment]
Also, here is my branch WIP: https://github.com/Conzar/nolo-osvr/tree/remapping_ids_for_steamvr
